# Generated by Django 3.2.15 on 2022-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=60)),
                ('nit', models.CharField(max_length=60)),
                ('representanteLegal', models.CharField(max_length=60)),
                ('eslogan', models.CharField(max_length=60)),
            ],
        ),
    ]
