# Generated by Django 3.2.15 on 2022-10-13 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observacion', models.TextField()),
                ('estado', models.BooleanField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
                ('numeroPersonas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('valor', models.FloatField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='informacion',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='direccion',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='eslogan',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='nit',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='representanteLegal',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='telefono',
            field=models.CharField(max_length=7),
        ),
        migrations.CreateModel(
            name='Producto_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tipo_producto'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.FloatField()),
                ('medioPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta debito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia bancaria')], max_length=20)),
                ('estado', models.BooleanField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
