# Generated by Django 4.1.1 on 2022-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20221020_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor',
        ),
        migrations.AddField(
            model_name='producto_pedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto_pedido',
            name='observacion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipo_producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
